import SwiftUI

struct AdvancedDashboardView: View {
    @EnvironmentObject private var store: AdvancedStore
    @State private var selectedTab = 0
    private let tabs = ["Command", "Agents", "Pipelines", "Forex", "Neural"]
    var body: some View {
        ScrollView { VStack(alignment: .leading, spacing: 20) { overviewHeader; tabBar; Group { switch selectedTab { case 1: AgentConsoleView(); case 2: PipelineView(); case 3: ForexQuantView(); case 4: NeuralLabView(); default: CommandCenterView() } } }.padding(18).padding(.bottom, 30) }.scrollIndicators(.hidden)
    }
    private var overviewHeader: some View { HStack(alignment: .bottom) { SectionHeader(eyebrow: "F L Y E  /  O P E R A T I O N S", title: tabs[selectedTab]); Spacer(); Label("ON-DEVICE", systemImage: "cpu").font(.caption2.weight(.bold)).foregroundStyle(SystemFlyeTheme.cyan).padding(.horizontal, 10).padding(.vertical, 7).background(SystemFlyeTheme.cyan.opacity(0.12), in: Capsule()) } }
    private var tabBar: some View { ScrollView(.horizontal, showsIndicators: false) { HStack(spacing: 8) { ForEach(tabs.indices, id: \.self) { index in Button(tabs[index]) { selectedTab = index }.font(.caption.weight(.semibold)).foregroundStyle(selectedTab == index ? .black : .white.opacity(0.7)).padding(.horizontal, 14).padding(.vertical, 9).background(selectedTab == index ? SystemFlyeTheme.cyan : SystemFlyeTheme.panel, in: Capsule()) } } } }
}

struct CommandCenterView: View {
    @EnvironmentObject private var store: AdvancedStore
    var body: some View { VStack(alignment: .leading, spacing: 18) { LazyVGrid(columns: [GridItem(.flexible()), GridItem(.flexible())], spacing: 10) { MetricTile(label: "Agent runs", value: "\(store.runCount)", detail: "+18% this session", tint: .green); MetricTile(label: "Signal confidence", value: "92.4%", detail: "ensemble consensus", tint: SystemFlyeTheme.cyan); MetricTile(label: "Pipeline latency", value: "1.84s", detail: "p95 / local runtime", tint: .orange); MetricTile(label: "Neural epoch", value: "E\(store.neuralEpoch)", detail: "adaptive trainer", tint: SystemFlyeTheme.violet) }; HStack { Text("LIVE EVENT STREAM").font(.caption2.weight(.bold)).tracking(1.5); Spacer(); Circle().fill(.green).frame(width: 7, height: 7); Text("streaming").font(.caption).foregroundStyle(.secondary) }.foregroundStyle(.white); EventRow(icon: "waveform.path.ecg", title: "ORBIT resolved EUR/USD regime", detail: "trend continuation · 94% confidence", color: .cyan); EventRow(icon: "arrow.triangle.2.circlepath", title: "Stress test checkpoint complete", detail: "12 paths · max drawdown 3.8%", color: .orange); EventRow(icon: "brain", title: "Neural Lab adapted feature weights", detail: "momentum +0.06 · volatility -0.02", color: .purple) } }
}

struct EventRow: View { let icon: String; let title: String; let detail: String; let color: Color; var body: some View { HStack(spacing: 12) { Image(systemName: icon).font(.system(size: 16, weight: .semibold)).foregroundStyle(color).frame(width: 34, height: 34).background(color.opacity(0.13), in: RoundedRectangle(cornerRadius: 9)); VStack(alignment: .leading, spacing: 3) { Text(title).font(.subheadline.weight(.semibold)).foregroundStyle(.white); Text(detail).font(.caption).foregroundStyle(.secondary) }; Spacer(); Image(systemName: "chevron.right").font(.caption).foregroundStyle(.secondary) }.padding(12).background(SystemFlyeTheme.panel, in: RoundedRectangle(cornerRadius: 13)) }

struct AgentConsoleView: View { @EnvironmentObject private var store: AdvancedStore; var body: some View { VStack(alignment: .leading, spacing: 12) { Text("Agents are constrained by explicit tools and policy gates.").font(.subheadline).foregroundStyle(.secondary); ForEach(store.agents) { agent in VStack(alignment: .leading, spacing: 12) { HStack { Circle().fill(agent.accent).frame(width: 10, height: 10); Text(agent.name).font(.headline.weight(.bold)); Spacer(); Text(agent.status.rawValue).font(.caption2.weight(.bold)).foregroundStyle(agent.status == .running ? .orange : .secondary) }; Text(agent.role).font(.subheadline).foregroundStyle(.secondary); HStack { ForEach(agent.tools, id: \.self) { Text($0).font(.caption2).padding(.horizontal, 8).padding(.vertical, 5).background(Color.white.opacity(0.06), in: Capsule()) } }; HStack { Label("Confidence \(Int(agent.confidence * 100))%", systemImage: "checkmark.shield").font(.caption).foregroundStyle(agent.accent); Spacer(); Button(agent.status == .paused ? "Resume" : "Run now") { store.runAgent(agent.id) }.buttonStyle(.borderedProminent).tint(agent.accent) } }.padding(15).background(SystemFlyeTheme.panel, in: RoundedRectangle(cornerRadius: 14)) } } } }

struct PipelineView: View { @EnvironmentObject private var store: AdvancedStore; var body: some View { VStack(alignment: .leading, spacing: 14) { HStack { Text("EUR/USD REGIME PIPELINE").font(.headline.weight(.bold)); Spacer(); Button("Run pipeline") { store.runCount += 1 }.buttonStyle(.borderedProminent).tint(SystemFlyeTheme.cyan) }; ForEach(Array(store.pipeline.enumerated()), id: \.element.id) { index, step in HStack(alignment: .top, spacing: 12) { VStack { Image(systemName: step.state == .complete ? "checkmark" : step.state == .active ? "play.fill" : "circle").font(.caption.weight(.bold)).foregroundStyle(step.state == .complete ? .green : step.state == .active ? .orange : .secondary).frame(width: 28, height: 28).background(Color.white.opacity(0.06), in: Circle()); if index < store.pipeline.count - 1 { Rectangle().fill(SystemFlyeTheme.line).frame(width: 1, height: 38) } }; VStack(alignment: .leading, spacing: 5) { HStack { Text(step.name).font(.subheadline.weight(.semibold)); Spacer(); Text(step.duration).font(.caption.monospacedDigit()).foregroundStyle(.secondary) }; Text("\(step.kind)  ·  \(step.detail)").font(.caption).foregroundStyle(.secondary) } } } }.padding(16).background(SystemFlyeTheme.panel, in: RoundedRectangle(cornerRadius: 16)) } }

struct ForexQuantView: View { @EnvironmentObject private var store: AdvancedStore; var body: some View { VStack(alignment: .leading, spacing: 16) { HStack { Text(store.selectedPair).font(.title3.weight(.bold)); Spacer(); Label("MARKET OPEN", systemImage: "circle.fill").font(.caption2.weight(.bold)).foregroundStyle(.green) }; Sparkline(values: [2, 3, 2.4, 4, 3.5, 5, 4.8, 6, 6.8, 6.1, 7.2]).stroke(SystemFlyeTheme.cyan, style: StrokeStyle(lineWidth: 2.5, lineCap: .round, lineJoin: .round)).frame(height: 90).background(Color.white.opacity(0.03), in: RoundedRectangle(cornerRadius: 12)); ForEach(store.signals) { signal in HStack { VStack(alignment: .leading, spacing: 4) { Text(signal.pair).font(.subheadline.weight(.bold)); Text("\(signal.regime) regime · risk \(signal.risk)").font(.caption).foregroundStyle(.secondary) }; Spacer(); VStack(alignment: .trailing, spacing: 4) { Text(signal.direction).font(.caption.weight(.bold)).foregroundStyle(signal.direction == "LONG" ? .green : signal.direction == "SHORT" ? .orange : .secondary); Text("\(Int(signal.score * 100)) score").font(.caption2.monospacedDigit()).foregroundStyle(.secondary) } }.padding(13).background(SystemFlyeTheme.panel, in: RoundedRectangle(cornerRadius: 13)) } } } }

struct NeuralLabView: View { @EnvironmentObject private var store: AdvancedStore; var body: some View { VStack(alignment: .leading, spacing: 16) { HStack { VStack(alignment: .leading, spacing: 4) { Text("NEURAL LAB").font(.headline.weight(.bold)); Text("Small adaptive model · fully on device").font(.caption).foregroundStyle(.secondary) }; Spacer(); Button(store.isTraining ? "Training…" : "Train model") { store.train() }.buttonStyle(.borderedProminent).tint(SystemFlyeTheme.violet) }; HStack(spacing: 10) { MetricTile(label: "Epoch", value: "\(store.neuralEpoch)", detail: "of 50", tint: .purple); MetricTile(label: "Accuracy", value: "\(Int(store.signalBias * 100))%", detail: "validation", tint: .green) }; VStack(alignment: .leading, spacing: 10) { Text("FEATURE ACTIVATION").font(.caption2.weight(.bold)).tracking(1.4).foregroundStyle(.secondary); ForEach([("Momentum", 0.82), ("Volatility", 0.64), ("Liquidity", 0.48), ("Sentiment", 0.72)], id: \.0) { feature, value in HStack { Text(feature).font(.caption); GeometryReader { proxy in Capsule().fill(Color.white.opacity(0.08)).overlay(alignment: .leading) { Capsule().fill(SystemFlyeTheme.violet).frame(width: proxy.size.width * value) } }.frame(height: 7); Text("\(Int(value * 100))%").font(.caption2.monospacedDigit()).frame(width: 36, alignment: .trailing) } } }.padding(16).background(SystemFlyeTheme.panel, in: RoundedRectangle(cornerRadius: 15)) } } }
